class AddSafetyTechnologyColumnsToSafetyTechnologies < ActiveRecord::Migration[7.1]
  def change
    add_column :safety_technologies, :airbag_count, :string, comment: 'Số túi khí'
    add_column :safety_technologies, :rear_sensor, :string, comment: 'Cảm biến lùi'
    add_column :safety_technologies, :central_locking, :string, comment: 'Khóa cửa trung tâm'
    add_column :safety_technologies, :cruise_control, :string, comment: 'Kiểm soát hành trình (Cruise Control)'
    add_column :safety_technologies, :adaptive_cruise_control, :string, comment: 'Kiểm soát hành trình thích ứng (Adaptive Cruise Control)'
    add_column :safety_technologies, :abs_brakes, :string, comment: 'Chống bó cứng phanh (ABS)'
    add_column :safety_technologies, :emergency_brake_assist, :string, comment: 'Hỗ trợ lực phanh khẩn cấp (BA)'
    add_column :safety_technologies, :ebd, :string, comment: 'Phân phối lực phanh điện tử (EBD)'
    add_column :safety_technologies, :esp, :string, comment: 'Cân bằng điện tử (VSC, ESP)'
    add_column :safety_technologies, :tcs, :string, comment: 'Kiểm soát lực kéo (chống trượt, kiểm soát độ bám đường TCS)'
    add_column :safety_technologies, :hill_start_assist, :string, comment: 'Hỗ trợ khởi hành ngang dốc'
    add_column :safety_technologies, :hill_descent_control, :string, comment: 'Hỗ trợ đổ đèo'
    add_column :safety_technologies, :blind_spot_warning, :string, comment: 'Cảnh báo điểm mù'
    add_column :safety_technologies, :rear_view_camera, :string, comment: 'Camera lùi'
    add_column :safety_technologies, :camera_360, :string, comment: 'Camera 360'
    add_column :safety_technologies, :lane_watch, :string, comment: 'Camera quan sát làn đường (LaneWatch)'
    add_column :safety_technologies, :lane_departure_warning, :string, comment: 'Cảnh báo chệch làn đường'
    add_column :safety_technologies, :lane_keeping_assist, :string, comment: 'Hỗ trợ giữ làn'
    add_column :safety_technologies, :automatic_collision_prevention, :string, comment: 'Hỗ trợ phanh tự động giảm thiểu va chạm'
    add_column :safety_technologies, :cross_traffic_warning_reverse, :string, comment: 'Cảnh báo phương tiện cắt ngang khi lùi'
    add_column :safety_technologies, :driver_drowsiness_warning, :string, comment: 'Cảnh báo tài xế buồn ngủ'
    add_column :safety_technologies, :isofix_hooks, :string, comment: 'Móc ghế an toàn cho trẻ em Isofix'
    add_column :safety_technologies, :tire_pressure_sensor, :string, comment: 'Cảm biến áp suất lốp'
    add_column :safety_technologies, :front_distance_sensor, :string, comment: 'Cảm biến khoảng cách phía trước'
    add_column :safety_technologies, :front_collision_warning, :string, comment: 'Cảnh báo tiền va chạm'
    add_column :safety_technologies, :wind_stability, :string, comment: 'Ổn định thân xe khi gió thổi ngang'
    add_column :safety_technologies, :lane_change_support, :string, comment: 'Hỗ trợ chuyển làn'
    add_column :safety_technologies, :sudden_acceleration_prevention, :string, comment: 'Chống tăng tốc đột ngột (đạp nhầm chân ga)'
    add_column :safety_technologies, :front_vehicle_departure_alert, :string, comment: 'Thông báo xe phía trước khởi hành'
    add_column :safety_technologies, :front_vehicle_start_alert, :string, comment: 'Thông báo xe trước khởi hành'
    add_column :safety_technologies, :automatic_lane_change, :string, comment: 'Tự động chuyển làn'
    add_column :safety_technologies, :door_traffic_warning, :string, comment: 'Cảnh báo giao thông khi mở cửa'
    add_column :safety_technologies, :limited_slip_differential, :string, comment: 'Vi sai hạn chế trượt LSD'
    add_column :safety_technologies, :traffic_sign_recognition, :string, comment: 'Nhận diện biển báo giao thông'
    add_column :safety_technologies, :automatic_parking_support, :string, comment: 'Hỗ trợ đỗ xe tự động'
    add_column :safety_technologies, :off_road_cruise_control, :string, comment: 'Kiểm soát hành trình trên đường địa hình'
    add_column :safety_technologies, :front_rear_sensors, :string, comment: 'Hệ thống cảm biến trước/sau'
    add_column :safety_technologies, :blind_spot_camera, :string, comment: 'Camera quan sát điểm mù'
    add_column :safety_technologies, :active_yaw_control, :string, comment: 'Kiểm soát vào cua chủ động AYC (Active Yaw Control)'
    add_column :safety_technologies, :rear_automatic_emergency_braking, :string, comment: 'Phanh tự động khẩn cấp sau va chạm'
    add_column :safety_technologies, :blind_spot_display, :string, comment: 'Hiển thị điểm mù trên màn hình (BVM)'
    add_column :safety_technologies, :front_cross_traffic_warning, :string, comment: 'Cảnh báo phương tiện phía trước khởi hành'
  end
end
