class AddColumnsToInteriors < ActiveRecord::Migration[7.1]
  def change
    add_column :interiors, :seat_material, :string
    add_column :interiors, :driver_seat_adjustment, :string
    add_column :interiors, :memory_driver_seat_position, :string
    add_column :interiors, :passenger_seat_adjustment, :string
    add_column :interiors, :driver_dashboard, :string
    add_column :interiors, :steering_wheel_material, :string
    add_column :interiors, :second_row_seats, :string
    add_column :interiors, :third_row_seats, :string
    add_column :interiors, :air_conditioning, :string
    add_column :interiors, :one_touch_windows, :string
    add_column :interiors, :infotainment_screen, :string
    add_column :interiors, :speaker_system, :string
    add_column :interiors, :double_layer_glass, :string
    add_column :interiors, :tinted_glass, :string
    add_column :interiors, :rear_entertainment_screen, :string
    add_column :interiors, :rear_passenger_screen, :string
    add_column :interiors, :smartphone_integration, :string
    add_column :interiors, :additional_features, :string
    add_column :interiors, :steering_adjustment, :string
    add_column :interiors, :interior_color, :string
    add_column :interiors, :driver_seat_massage, :string
    add_column :interiors, :passenger_seat_massage, :string
    add_column :interiors, :driver_seat_cooling, :string
    add_column :interiors, :passenger_seat_cooling, :string
    add_column :interiors, :driver_steering_controls, :string
    add_column :interiors, :smart_key, :string
    add_column :interiors, :push_button_start, :string
    add_column :interiors, :rear_seat_vents, :string
    add_column :interiors, :sunroof, :string
    add_column :interiors, :panoramic_sunroof, :string
    add_column :interiors, :auto_dimming_rearview_mirror, :string
    add_column :interiors, :front_armrest, :string
    add_column :interiors, :rear_armrest, :string
    add_column :interiors, :apple_carplay, :string
    add_column :interiors, :android_auto, :string
    add_column :interiors, :voice_command, :string
    add_column :interiors, :hands_free_calling, :string
    add_column :interiors, :wifi_hotspot, :string
    add_column :interiors, :aux_connection, :string
    add_column :interiors, :usb_connection, :string
    add_column :interiors, :bluetooth_connection, :string
    add_column :interiors, :am_fm_radio, :string
    add_column :interiors, :wireless_charging, :string
    add_column :interiors, :power_tailgate, :string
    add_column :interiors, :remote_start, :string
    add_column :interiors, :air_filter, :string
    add_column :interiors, :steering_wheel_heating, :string
    add_column :interiors, :navigation, :string
    add_column :interiors, :air_quality_control, :string
    add_column :interiors, :gesture_control, :string
    add_column :interiors, :center_display, :string
    add_column :interiors, :power_driver_seat_adjustment, :string
    add_column :interiors, :power_passenger_seat_adjustment, :string
    add_column :interiors, :wifi_connectivity, :string
    add_column :interiors, :interior_ambient_lighting, :string
    add_column :interiors, :apple_carplay_android_auto, :string
    add_column :interiors, :interior_material, :string
    add_column :interiors, :starry_ceiling, :string
    add_column :interiors, :alcantara_ceiling, :string
    add_column :interiors, :driver_cabin_and_passenger_compartment_partition_with_tv, :string
    add_column :interiors, :independent_seats_with_leg_support, :string
    add_column :interiors, :virtual_assistant, :string
    add_column :interiors, :steering_memory, :string
    add_column :interiors, :rear_seat_heating_cooling, :string
    add_column :interiors, :front_seat_heating_cooling, :string
    add_column :interiors, :rear_seats_heating, :string
    add_column :interiors, :rear_sunshade, :string
    add_column :interiors, :rear_door_sunshade, :string
    add_column :interiors, :power_outlet_230V, :string
  end
end
